// src/core/feedback/avaliador.js

/**
 * Analisa as instruções executadas e propõe melhorias para a próxima rodada.
 * Pode ser usado no modo "self-feedback".
 */

export function avaliarExecucao({ arquivos, log, tempo }) {
    const sugestoes = [];
  
    if (!arquivos?.length) {
      sugestoes.push('Nenhum arquivo foi criado. Verifique se a instrução foi interpretada corretamente.');
    }
  
    if (log.includes('Erro ao processar')) {
      sugestoes.push('Detectado erro de execução. Tente simplificar ou revisar o prompt.');
    }
  
    if (tempo > 3000) {
      sugestoes.push('A execução demorou demais. Considere dividir a tarefa em blocos menores.');
    }
  
    if (arquivos.some(a => a.includes('AutoGenerated'))) {
      sugestoes.push('Crie nomes de arquivos mais específicos para facilitar manutenções futuras.');
    }
  
    return {
      score: 100 - sugestoes.length * 10,
      sugestoes
    };
  }
  